### ISSUE TITLE
Ideas for enhancements to atc-sim

### ISSUE THREAD

**Issue by andersjc01** [fragfest/game-atc#1]
Played atc-sim for a few hours and I have some ideas for enhancements to make the game more user-friendly (if that is the goal).

1) Consistent input.  There's 'L' for land, 'T' for take off, 'S' for speed but for headings and altitude it's 'C'.  Suggest to scrap C and add 'H' and 'A'
2) Show icons for planes on runway before they take off.
3) If a plane has accepted commands for landing, the icon turns green

**Comment by fragfest** [comment]
1. Created a different ticket for tracking the bigger keyboard shortcut features #3
2. Should come up again when creating departing aircraft features
3. Tracked in ticket #2
